/**
 * The registry. Generated by `scripts/register_scenes.py` — do not hand-edit.
 *
 * This placeholder is what a fresh project starts with, so the template
 * type-checks and Studio opens before a single scene exists. Running the
 * register script overwrites the whole file.
 *
 * The timeline in here is the voiced one: `start` and `duration` come from the
 * real length of each scene's audio, measured after synthesis. Nothing
 * estimates a duration, and no scene may set its own — a scene that ran long
 * would push every scene after it out of sync with its own voice.
 */
import type React from "react";

/** One sentence of narration, in seconds relative to the start of its scene. */
export type SceneSegment = {
  text: string;
  start: number;
  end: number;
};

/** What every generated A-roll scene component receives. */
export type SceneProps = {
  /** This scene's narration, sentence by sentence, with real timings. */
  segments: SceneSegment[];
  /** How long the scene lasts, in frames. Animations must fit inside it. */
  durationInFrames: number;
};

type SceneBase = {
  id: string;
  /** Seconds from the start of the film. */
  start: number;
  /** Seconds. The length of this scene's audio. */
  duration: number;
  /** Relative to the project root, e.g. "audio/scene-001.wav". */
  audioSrc: string;
  segments: SceneSegment[];
};

export type GeneratedSceneItem =
  | (SceneBase & {
      rollType: "a-roll";
      Component: React.FC<SceneProps>;
    })
  | (SceneBase & {
      rollType: "b-roll";
      /** Relative to `public/`, e.g. "broll/scene-004.mp4". */
      videoSrc: string;
      /** How long the source clip actually is, in seconds. */
      mediaDuration: number;
    });

export const generatedScenes: GeneratedSceneItem[] = [];

export const totalDuration = 0;
